### ISSUE TITLE
Design the database schema

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/query-service#7]
# Need
* As a user of the Query Service
* I want a database table schema that is easy and intuitive to use
* so that I can query for metadata efficiently.

# Approach
- [ ] Decide on how raw bundle metadata will be divided up into tables in the database

**Comment by mweiden** [comment]
Preliminary thoughts

* Assays, donors... all sub-entities of bundle have a many-to-many relationship with bundles.
* Can we assume that projects have a one-to-many relationship with bundles?

**Comment by malloryfreeberg** [comment]
> Can we assume that projects have a one-to-many relationship with bundles?

Yes, I think this is a fair assumption. It is possible to have a 1-to-1 project:bundle (if the project just has 1 10X assay, for example), but most cases will have 1-to-many project:bundle ratio. 

FWIW, I think @tburdett and @daniwelter have been pushing for a place to record assumptions like this.

**Comment by tburdett** [comment]
> Can we assume that projects have a one-to-many relationship with bundles?

I would say that one to many is not a safe assumption. There's no good reason (besides current practice) that restricts this. For example, a secondary analysis bundle will contain data from a submitter and there is nothing to say that the primary data generation project and the analysis project must be the same.

There's also a variety of potential bundle types besides those in the system already. [This document](https://docs.google.com/document/d/1101ia2SmqbXMkbEeAVdLCUlMvfo95oAaclbUbNLTths/edit#heading=h.vn52s6vshywv) outlines a proposal of various expected bundle types over the course of the project. I'm expecting bundles to be a moving target.

**Comment by tburdett** [comment]
Incidentally, is there a reason your user story describes a database schema? Does this service have users you can point to that are somehow constrained to SQL? This feels like both an implementation detail and a poor design choice for describing semi-structured data with a rapidly evolving schema and a high proportion of many to many relations and self-joins.

**Comment by mweiden** [comment]
@tburdett @malloryfreeberg thank you for the information.

@tburdett Re. your design questions, please check out our [SQL technical demo for dealing with rapidly evolving metadata](https://docs.google.com/presentation/d/1VGFvIznbHkYRnp8uxfIUCh3CyS4YWqkQugzF2WPcNJY/edit). I don't think it will be what you expect.

Importantly, we will have to make a few adjustments to the schema outlined in that deck to deal with many-to-many relationships.

**Comment by tburdett** [comment]
Thanks for the links to the slides. Really Interesting! Here's my immediate thoughts

- Where did you get the metadata for this demo? It's waaaay out of date (assays were phased out very early this year). I expect the current stable model to have a big impact on your benchmarking as the documents themselves are no longer partially denormalised before landing in the DSS (i.e. bundles contain multiple biomaterial documents instead of one biomaterial document containing an array).
- The proposed schema (assuming the above updates) aligns exactly to the ingest and metadata shared "core domain model" and we should reflect this on the various charters if you decide to go this route
- With a query service designed like this, I really think the overall DCP design needs to be revisited. This design is conceptually identical to the datastore behind ingest (which uses Mongo, with multiple collections corresponding to the tables in your schema here). This puts us in the crazy situation I anticipated at the January DCP meeting in Boston: all the metadata in the DCP will be denormalised by ingest to push it into the DSS, only for the query service to renormalise it all into an identical representation it started off in.

Would it be a good idea for you to give an overview of this proposed design on the next tech arch call? I personally think it would be great to discuss some of these overarching design issues more widely and have the group thinking about whether the wider DCP design is working well for us.

**Comment by mweiden** [comment]
@tburdett I appreciate your interest and advice.

Let's have a call on these topics. I can answer your questions and catch you up on some context.

**Comment by MDunitz** [comment]
can you add me to the call (if it hasnt occurred yet)

**Comment by MDunitz** [comment]
https://www.lucidchart.com/invitations/accept/86cf4e3c-eca7-4364-b777-6b8d8127cb1e

**Comment by mweiden** [comment]
@MDunitz great ty
